# Generated by Django 4.2.1 on 2023-05-09 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otra'), ('N', 'Preferiría no contestar')], max_length=10, null=True, verbose_name='elige tu sexo*')),
                ('fecha_de_nacimiento', models.DateField(null=True, verbose_name='fecha de nacimiento*')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre*')),
                ('apellido', models.CharField(max_length=50, unique=True, verbose_name='apellido*')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='dirección donde se reúnen frecuentemente')),
                ('casa_apto', models.CharField(blank=True, max_length=100, verbose_name='dirección donde se reúnen frecuentemente')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='dirección donde se reúnen frecuentemente')),
                ('activo', models.BooleanField(default=True, verbose_name='¿El tipo se encuentra activo?')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudad', to='cities_light.city', verbose_name='¿En qué ciudad se encuentra?*')),
                ('pais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pais', to='cities_light.country', verbose_name='¿En qué país se encuentra?*')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region', to='cities_light.region', verbose_name='¿En qué región se encuentra?*')),
            ],
        ),
    ]
