# Generated by Django 4.2.1 on 2023-05-11 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_email_alter_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.EmailValidator('Correo electrónico inválido')], verbose_name='Email'),
        ),
    ]
